select * from cust_shopping ;

### what is the revenue generated by male vs female###
select GENDER ,sum(PURCHASE_AMT) as revenue
FROM cust_shopping
group by gender;


# which customer used discount but stiil spend more than avg purchse amt

select customer_id,purchase_amt 
from cust_shopping 
where  discount_applied = 'Yes' and purchase_amt >= (select avg(purchase_amt) from cust_shopping) ;

#which rthe top 5 productswiththe highest avg review rating

SELECT *
FROM (
    SELECT item_purchased,ROUND( AVG(review_rating),2) AS avg_review_rating
    FROM cust_shopping
    GROUP BY item_purchased
    ORDER BY AVG(review_rating) DESC
)
WHERE ROWNUM <= 5;


##compare thr avg purchase amts b/w standard and express shipping

select shipping_type,ROUND(avg(purchase_amt) ,2)
from cust_shopping
where shipping_type in ('Standard','Express')
group by shipping_type ;

##do subcribed customer spend more? avg spend and total revenue betweem subcribers and non-subcribers

select subscription_status ,
count(customer_id),
round(avg(purchase_amt),2) as avg_spend,
round(sum(purchase_amt),2) as total_revenue
from cust_shopping
group by subscription_status
order by total_revenue , avg_spend desc;


##which 5 products have highest % of purchase with discount applied
select *
from (
select item_purchased,
ROUND(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from cust_shopping
group by item_purchased
order by discount_rate desc)
where rownum <=5;

#segment customer new,returning and loyal based on their total no of previous purchases and show the count of each segment


WITH customer_type AS (
    SELECT customer_id, previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM cust_shopping
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

##which are the most purchased  product in each category
WITH product_count AS (
    SELECT category, item_purchased,
           COUNT(*) AS purchase_count
    FROM cust_shopping
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT category, item_purchased, purchase_count,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY purchase_count DESC) AS rn
    FROM product_count
)
SELECT category, item_purchased, purchase_count
FROM ranked_products
WHERE rn <=3;

##are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from cust_shopping
where previous_purchases > 5
group by subscription_status;

##what is the revenue contribution of each age group
WITH age_group AS (
    SELECT 
        CASE 
            WHEN age < 20 THEN 'Under 20'
            WHEN age BETWEEN 20 AND 35 THEN '20-35'
            WHEN age BETWEEN 36 AND 50 THEN '36-50'
            ELSE '50+'
        END AS age_group,
        purchase_amt
    FROM cust_shopping
)
SELECT 
    age_group,
    SUM(purchase_amt) AS total_revenue
FROM age_group
GROUP BY age_group
ORDER BY total_revenue DESC;